### ISSUE TITLE
Optimize `_authorized()` for common case

### ISSUE THREAD

**Issue by horsefacts** [kalidao/multi-sig#122]
`Keep` calls an internal `_authorized()` function internally in most of its public functions. This function first checks whether the caller is a core key owner, then whether the caller is an authorized ID key owner:

```solidity
    /// @dev Access control check for ID key balance holders.
    function _authorized() internal view virtual returns (bool) {
        if (_coreKeyHolder() || balanceOf[msg.sender][uint32(msg.sig)] != 0) 
            return true;
        else revert Unauthorized();
    }

    /// @dev Core access control check.
    /// Initalizes with `address(this)` having implicit permission
    /// without writing to storage by checking `totalSupply()` is zero.
    /// Otherwise, this permission can be set to additional accounts,
    /// including retaining `address(this)`, via `mint()`.
    function _coreKeyHolder() internal view virtual returns (bool) {
        return
            (totalSupply[CORE_KEY] == 0 && msg.sender == address(this)) ||
            balanceOf[msg.sender][CORE_KEY] != 0;
    }
```

If we inline the internal call to `_coreKeyHolder`, the `if` condition is equivalent to:

```solidity
(totalSupply[CORE_KEY] == 0 && msg.sender == address(this)) || 
 balanceOf[msg.sender][CORE_KEY] != 0 || 
 balanceOf[msg.sender][uint32(msg.sig)] != 0;
```

This means each call to `_authorized()` checks the following conditions in order:

1. `totalSupply[CORE_KEY] == 0`
2. `msg.sender == address(this)`
3. `balanceOf[msg.sender][CORE_KEY] !=0`
4. `balanceOf[msg.sender][uint32(msg.sig)] != 0`

Ideally, these conditions should be ordered with the most common case first. If ID key owners are more likely to call authenticated functions than the core key holder, consider reversing the order of this check, which will short circuit and skip the call to `_coreKeyHolder()` if the first clause returns `true`:

```solidity
    /// @dev Access control check for ID key balance holders.
    function _authorized() internal view virtual returns (bool) {
        if (balanceOf[msg.sender][uint32(msg.sig)] != 0 || _coreKeyHolder()) 
            return true;
        else revert Unauthorized();
    }
```

Similarly, if it's more likely that the `CORE_KEY` supply is nonzero, consider ordering the checks in `_coreKeyHolder()` with the common case first:

```solidity
    function _coreKeyHolder() internal view virtual returns (bool) {
        return balanceOf[msg.sender][CORE_KEY] != 0 || 
            (totalSupply[CORE_KEY] == 0 && msg.sender == address(this));
    }
```

(However, I'm not sure this is actually the case—you know better than I do about the expected behavior of end users).

You're all gonna hate me for this suggestion because it will blow up your gas snapshots: existing tests mostly assume that the caller is `keep` rather than an ID token user, so you will see gas costs increase for most functions as reported by Forge snapshots and the gas report. But this is probably a case where the behavior captured by tests is not representative of usage patterns in the real world.

**Comment by z0r0z** [comment]
Good stuff @horsefacts! I am noticing some savings with the chunk as so:

![image](https://user-images.githubusercontent.com/92001561/198965685-f545ef1a-5150-475d-b7a4-f2fead936830.png)

In terms of expected order and frequency of callers to authorized functions ....

Usually this will be by the Keep itself. So, a call to `execute()` that does managerial things to contract itself like adding and removing `SIGN_KEY` holders who are basically like traditional multisig key signers.

This is why we check `CORE_KEY` first for authorization. 

Otherwise, I expect that helper contracts like crowdsale will hold the minting key, etc., and so that is next.

**Comment by z0r0z** [comment]
thanks horse! https://github.com/kalidao/keep/commit/d2b527899dbbceb147354a115af29d77646853eb
